### ISSUE TITLE
need of styling to home page

### ISSUE THREAD

**Issue by panditshivammishra** [ShwetKhatri2001/AR-Webstore#212]
### What's the style idea?

adding dark and light mode with some animation in home page for intro

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CODE_OF_CONDUCT.md)
- [X] I'm a SWOC'24 contributor
- [X] I want to work on this issue

**Comment by ShwetKhatri2001** [comment]
Let's not go for the dark/light mode option yet, since it will require changes all across the app and contributors also need to cover both at a time in the future which will lead to new issues. It will be easy to do at the later stage of development.

Animations can be added for the cards, links, etc present on the home page. I'm assigning you for that.
