### ISSUE TITLE
UI of website 

### ISSUE THREAD

**Issue by vinayakmalviya21** [ShwetKhatri2001/AR-Webstore#91]
### Description

Content of website can be in center so it will look good. Please assign this issue to me.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by vinayakmalviya21** [comment]
I have resolve this issue. Please review it and merge my PR. Also, give gssoc23 label.

**Comment by ShwetKhatri2001** [comment]
@vinayakmalviya21 It's good that you're very interested to contribute to the project but this issue was not assigned to you. So, kindly wait till it gets assigned and then raise a PR. 

Also, The changes mentioned in that PR are already covered under other issues which are assigned as well. So, next time onwards please go through the existing issues first and raise a new one if it's not covered already.
